---
title: "Цели и задачи изучения R"
author: "Ilya Sattarov"
date: "06 08 2019"
output:
  pdf_document: default
  html_document: default
header-includes:
- \usepackage[russian]{babel}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Изучение R имеет для меня как чисто прикладные задачи, так и более общие. Конечно, хочется надеятся, что на работе эти знания и навыки пригодятся (а это зависит не только от меня, но и от того, примет ли руководство новые методы), но в любом случае хороший курс для повторения статистики и как упражнене для мозгов. 

## Текущие цели и задачи:
* построение эконометрических моделей и проверка статестических гипотез для прогнозирования инвестицоинных процессов на текущей работе
* применение инструментов анализа данных в трейдинге

## Перспективные цели и задачи:
* умение применять R позволит в более короткие сроки сделать исследование для диссертации (в случае необходимости)
* в перспективе R будет плюсом при поиске работы, связанной с анализом данных или просто с более глубокой аналитикой
